workflows:
  ios-release:
    name: "iOS Release (Data Jury)"
    max_build_duration: 60

    environment:
      node: 22
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.datajury.app
      vars:
        BUNDLE_ID: "com.datajury.app"
        TEAM_ID: "R8W6XUCMDD"

    integrations:
      app_store_connect: codemagic

    scripts:
      - name: "Install dependencies"
        script: |
          set -euo pipefail
          npm ci

      - name: "Debug Capacitor versions"
        script: |
          set -euo pipefail
          node -v
          npm -v
          npm ls @capacitor/core @capacitor/ios @capacitor/cli || true

      - name: "Build Next.js (optional)"
        script: |
          set -euo pipefail
          npm run build || echo "Next build skipped"

      - name: "Compute numeric build number"
        script: |
          set -euo pipefail
          BUILD_NUM_LOCAL="$(date +%s)"
          echo "BUILD_NUM=$BUILD_NUM_LOCAL" >> "$CM_ENV"
          echo "Computed BUILD_NUM=$BUILD_NUM_LOCAL"

      - name: "Capacitor sync iOS"
        script: |
          set -euo pipefail
          npx cap sync ios

      - name: "Install Codemagic CLI tools"
        script: |
          set -euo pipefail
          python3 -m pip install --user codemagic-cli-tools
          export PATH="$HOME/Library/Python/3.12/bin:$HOME/Library/Python/3.11/bin:$HOME/Library/Python/3.10/bin:$PATH"
          codemagic --version || true

      - name: "Use Codemagic uploaded signing files"
        script: |
          set -euo pipefail
          export PATH="$HOME/Library/Python/3.12/bin:$HOME/Library/Python/3.11/bin:$HOME/Library/Python/3.10/bin:$PATH"

          keychain initialize
          xcode-project use-profiles --project ios/App/App.xcodeproj

          echo "Available signing identities:"
          security find-identity -v -p codesigning || true

      - name: "Force numeric CFBundleVersion (all Info.plist)"
        script: |
          set -euo pipefail
          : "${BUILD_NUM:?BUILD_NUM not set}"

          while IFS= read -r PLIST; do
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUM" "$PLIST" 2>/dev/null \
              || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $BUILD_NUM" "$PLIST"
          done < <(find ios -name "Info.plist")

      - name: "Archive (SPM: project) signed"
        script: |
          set -euo pipefail
          : "${BUILD_NUM:?BUILD_NUM not set}"

          rm -rf build
          mkdir -p build

          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath build/App.xcarchive \
            COMPILER_INDEX_STORE_ENABLE=NO \
            CURRENT_PROJECT_VERSION="$BUILD_NUM" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            archive | tee build/xcodebuild_archive.log

      - name: "Create PrivacyInfo.xcprivacy (CI generated)"
        script: |
          set -euo pipefail
          mkdir -p build/privacy

          cat > build/privacy/PrivacyInfo.xcprivacy <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>NSPrivacyTracking</key>
            <false/>
            <key>NSPrivacyTrackingDomains</key>
            <array/>
            <key>NSPrivacyCollectedDataTypes</key>
            <array/>
            <key>NSPrivacyAccessedAPITypes</key>
            <array/>
          </dict>
          </plist>
          EOF

          ls -la build/privacy/PrivacyInfo.xcprivacy

      - name: "Inject PrivacyInfo.xcprivacy into frameworks + re-sign (auto identity)"
        script: |
          set -euo pipefail
          set -x

          SRC="build/privacy/PrivacyInfo.xcprivacy"
          test -f "$SRC"

          APP_DIR="build/App.xcarchive/Products/Applications/App.app"
          test -d "$APP_DIR"

          echo "=== Embedded frameworks found in App.app ==="
          find "$APP_DIR" -maxdepth 4 -type d -name '*.framework' -print || true

          CAP_FW="$(find "$APP_DIR" -maxdepth 5 -type d -name "Capacitor.framework" | head -n 1 || true)"
          if [ -z "$CAP_FW" ]; then
            echo "❌ Capacitor.framework not found"
            exit 1
          fi

          COR_FW="$(find "$APP_DIR" -maxdepth 5 -type d -name "Cordova.framework" | head -n 1 || true)"

          cp -f "$SRC" "$CAP_FW/PrivacyInfo.xcprivacy"
          ls -la "$CAP_FW/PrivacyInfo.xcprivacy"

          if [ -n "$COR_FW" ]; then
            cp -f "$SRC" "$COR_FW/PrivacyInfo.xcprivacy"
            ls -la "$COR_FW/PrivacyInfo.xcprivacy"
          fi

          # ✅ Auto-detect a valid codesign identity present in the current keychain
          echo "Available signing identities:"
          security find-identity -v -p codesigning || true

          SIGN_HASH="$(security find-identity -v -p codesigning \
            | grep -i "Apple Distribution" \
            | head -n 1 \
            | awk '{print $2}')"

          if [ -z "${SIGN_HASH:-}" ]; then
            # fallback: any identity
            SIGN_HASH="$(security find-identity -v -p codesigning | head -n 1 | awk '{print $2}')"
          fi

          if [ -z "${SIGN_HASH:-}" ]; then
            echo "❌ No codesigning identity found in keychain"
            exit 1
          fi

          echo "Using codesign identity hash: $SIGN_HASH"

          /usr/bin/codesign --force --sign "$SIGN_HASH" --timestamp=none "$CAP_FW"
          /usr/bin/codesign -vv "$CAP_FW"

          if [ -n "$COR_FW" ]; then
            /usr/bin/codesign --force --sign "$SIGN_HASH" --timestamp=none "$COR_FW"
            /usr/bin/codesign -vv "$COR_FW"
          fi

      - name: "Export IPA"
        script: |
          set -euo pipefail
          mkdir -p build/ipa

          cat > build/export_options.json <<'EOF'
          {
            "method": "app-store-connect",
            "signingStyle": "manual",
            "teamID": "R8W6XUCMDD",
            "signingCertificate": "Apple Distribution",
            "provisioningProfiles": {
              "com.datajury.app": "com.datajury.app"
            },
            "stripSwiftSymbols": true,
            "compileBitcode": false
          }
          EOF

          plutil -convert xml1 build/export_options.json -o build/export_options.plist
          plutil -lint build/export_options.plist

          xcodebuild \
            -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist build/export_options.plist \
            -exportPath build/ipa | tee build/xcodebuild_export.log

          find build -name "*.ipa" -print || true

      - name: "Verify IPA (privacy manifests)"
        script: |
          set -euo pipefail
          IPA_PATH="$(ls -1 build/ipa/*.ipa | head -n 1)"
          TMPDIR="$(mktemp -d)"
          unzip -q "$IPA_PATH" -d "$TMPDIR"
          echo "Privacy manifests found:"
          find "$TMPDIR/Payload/App.app" -maxdepth 6 -name "PrivacyInfo.xcprivacy" -print || true

    artifacts:
      - "build/ipa/*.ipa"
      - "build/*.log"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
