workflows:
  ios-release:
    name: iOS Release (Data Jury)
    max_build_duration: 60

    environment:
      node: 20
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.datajury.app

    integrations:
      app_store_connect: codemagic

    scripts:
      - name: Install dependencies
        script: |
          set -euo pipefail
          npm ci

      - name: Build Next.js (optional)
        script: |
          set -euo pipefail
          npm run build || echo "Next build skipped"

      - name: Sync Capacitor iOS
        script: |
          set -euo pipefail
          npx cap sync ios

      - name: Install Ruby 3 + CocoaPods (modern setup)
        script: |
          set -euo pipefail

          # Fix greadlink missing
          sudo mkdir -p /usr/local/bin
          sudo ln -sf /usr/bin/readlink /usr/local/bin/greadlink || true

          echo "Installing Ruby via Homebrew..."
          brew update
          brew install ruby

          RUBY_PREFIX="$(brew --prefix ruby)"
          export PATH="$RUBY_PREFIX/bin:$PATH"

          echo "Ruby:"
          ruby -v

          echo "Installing CocoaPods..."
          gem install cocoapods -N

          echo "Pod:"
          pod --version

          cd ios/App
          rm -rf Pods Podfile.lock
          pod repo update
          pod install --repo-update
          cd ../..

      - name: Build IPA
        script: |
          set -euo pipefail

          cat > export_options.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

          rm -rf build
          mkdir -p build

          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath build/App.xcarchive \
            -allowProvisioningUpdates \
            COMPILER_INDEX_STORE_ENABLE=NO \
            archive | tee build/xcodebuild_archive.log

          xcodebuild \
            -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist export_options.plist \
            -exportPath build/ipa | tee build/xcodebuild_export.log

    artifacts:
      - build/ipa/*.ipa
      - build/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
