workflows:
  ios-release:
    name: iOS Release (Data Jury)
    max_build_duration: 60

    environment:
      node: 20

    integrations:
      app_store_connect: codemagic

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build Next.js (optional)
        script: |
          npm run build || echo "Next build skipped"

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Build IPA
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/App.xcarchive archive

          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist /Users/builder/export_options.plist \
            -exportPath build/ipa

    artifacts:
      - build/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
