workflows:
  ios-release:
    name: iOS Release (Data Jury)
    max_build_duration: 60

    environment:
      node: 22
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.datajury.app

    integrations:
      app_store_connect: codemagic

    scripts:
      - name: Install dependencies
        script: |
          set -euo pipefail
          npm ci

      - name: Debug Capacitor versions (must be consistent)
        script: |
          set -euo pipefail
          node -v
          npm -v
          npm ls @capacitor/core @capacitor/ios @capacitor/cli || true

      - name: Build Next.js (optional)
        script: |
          set -euo pipefail
          npm run build || echo "Next build skipped"

      - name: Compute numeric build number (automatic)
        script: |
          set -euo pipefail
          BUILD_NUM_LOCAL="$(date +%s)"
          echo "BUILD_NUM=$BUILD_NUM_LOCAL" >> "$CM_ENV"
          echo "Computed BUILD_NUM=$BUILD_NUM_LOCAL"

      - name: Capacitor sync iOS
        script: |
          set -euo pipefail
          npx cap sync ios

      - name: CocoaPods install (fix rbenv shim + logs)
        script: |
          set -euo pipefail
          set -x

          ruby -v || true
          gem -v || true

          # Install CocoaPods for the current Ruby (Codemagic often uses rbenv)
          gem install cocoapods -N --no-document

          # If rbenv is present, refresh shims so `pod` becomes available on PATH
          rbenv rehash || true

          echo "PATH=$PATH"
          which ruby || true
          which gem || true
          which pod || true

          pod --version

          PODFILE="ios/App/Podfile"
          test -f "$PODFILE"

          echo "=== Podfile BEFORE patch ==="
          sed -n '1,220p' "$PODFILE"

          # Force iOS deployment target (keep your original intent)
          sed -i '' "s/platform :ios, '.*'/platform :ios, '16.0'/g" "$PODFILE" || true
          echo "Podfile platform now:"
          grep -n "platform :ios" "$PODFILE" || true

          cd ios/App
          rm -rf Pods Podfile.lock

          # Run pod install with verbose logging and capture to artifact
          mkdir -p ../../build

          set +e
          pod install --repo-update --verbose 2>&1 | tee ../../build/pod_install.log
          POD_STATUS="${PIPESTATUS[0]}"
          set -e

          if [ "$POD_STATUS" -ne 0 ]; then
            echo "❌ pod install failed with status $POD_STATUS"
            echo "=== Podfile AFTER patch ==="
            sed -n '1,260p' Podfile || true
            echo "=== LAST 200 lines of pod_install.log ==="
            tail -n 200 ../../build/pod_install.log || true
            exit "$POD_STATUS"
          fi

          # Fix rsync symlink issue in CocoaPods frameworks script (if present)
          sed -i '' 's/--links/--copy-links/g' "Pods/Target Support Files/Pods-App/Pods-App-frameworks.sh" || true
          cd ../..

      - name: Force numeric CFBundleVersion (all Info.plist)
        script: |
          set -euo pipefail
          : "${BUILD_NUM:?BUILD_NUM not set}"
          echo "Using BUILD_NUM=$BUILD_NUM"

          find ios -name "Info.plist" -print

          while IFS= read -r PLIST; do
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUM" "$PLIST" 2>/dev/null \
              || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $BUILD_NUM" "$PLIST"
            /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST" || true
          done < <(find ios -name "Info.plist")

      - name: Archive (manual signing)
        script: |
          set -euo pipefail
          : "${BUILD_NUM:?BUILD_NUM not set}"

          rm -rf build
          mkdir -p build

          echo "Archiving with BUILD_NUM=$BUILD_NUM"

          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath build/App.xcarchive \
            COMPILER_INDEX_STORE_ENABLE=NO \
            CURRENT_PROJECT_VERSION="$BUILD_NUM" \
            archive | tee build/xcodebuild_archive.log

      - name: Inject PrivacyInfo.xcprivacy into archive frameworks + re-sign
        script: |
          set -euo pipefail

          SRC="ios/privacy/PrivacyInfo.xcprivacy"
          test -f "$SRC"

          APP_DIR="build/App.xcarchive/Products/Applications/App.app"
          test -d "$APP_DIR"

          FW_DIR="$APP_DIR/Frameworks"
          test -d "$FW_DIR"

          echo "Frameworks in archive:"
          ls -la "$FW_DIR" || true

          # Targets Apple complains about:
          CAP_FW="$FW_DIR/Capacitor.framework"
          COR_FW="$FW_DIR/Cordova.framework"

          if [ ! -d "$CAP_FW" ]; then
            echo "❌ Capacitor.framework not found in archive Frameworks"
            exit 1
          fi
          if [ ! -d "$COR_FW" ]; then
            echo "❌ Cordova.framework not found in archive Frameworks"
            exit 1
          fi

          cp -f "$SRC" "$CAP_FW/PrivacyInfo.xcprivacy"
          cp -f "$SRC" "$COR_FW/PrivacyInfo.xcprivacy"

          echo "✅ Injected privacy manifests into archive:"
          ls -la "$CAP_FW/PrivacyInfo.xcprivacy"
          ls -la "$COR_FW/PrivacyInfo.xcprivacy"

          # Re-sign modified frameworks using the same identity available in keychain
          SIGN_ID="Apple Distribution: Jaime Randle (R8W6XUCMDD)"
          echo "Re-signing frameworks with: $SIGN_ID"
          /usr/bin/codesign --force --sign "$SIGN_ID" --timestamp=none "$CAP_FW"
          /usr/bin/codesign --force --sign "$SIGN_ID" --timestamp=none "$COR_FW"

          echo "Verifying codesign..."
          /usr/bin/codesign -vv "$CAP_FW"
          /usr/bin/codesign -vv "$COR_FW"

      - name: Export IPA
        script: |
          set -euo pipefail

          mkdir -p build/ipa

          cat > build/export_options.json <<'EOF'
          {
            "method": "app-store-connect",
            "signingStyle": "manual",
            "teamID": "R8W6XUCMDD",
            "signingCertificate": "Apple Distribution",
            "provisioningProfiles": {
              "com.datajury.app": "com.datajury.app"
            },
            "stripSwiftSymbols": true,
            "compileBitcode": false
          }
          EOF

          plutil -convert xml1 build/export_options.json -o build/export_options.plist
          plutil -lint build/export_options.plist

          xcodebuild \
            -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist build/export_options.plist \
            -exportPath build/ipa | tee build/xcodebuild_export.log

          echo "IPAs found:"
          find build -name "*.ipa" -print || true

      - name: Verify IPA (Info.plist + privacy manifests)
        script: |
          set -euo pipefail

          IPA_PATH="$(ls -1 build/ipa/*.ipa | head -n 1)"
          echo "IPA: $IPA_PATH"
          TMPDIR="$(mktemp -d)"
          unzip -q "$IPA_PATH" -d "$TMPDIR"

          APP_PLIST="$TMPDIR/Payload/App.app/Info.plist"
          echo "CFBundleVersion:"
          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$APP_PLIST"

          echo "Checking privacy manifests inside IPA frameworks..."
          ls -la "$TMPDIR/Payload/App.app/Frameworks/Capacitor.framework/PrivacyInfo.xcprivacy"
          ls -la "$TMPDIR/Payload/App.app/Frameworks/Cordova.framework/PrivacyInfo.xcprivacy"

          echo "✅ OK"

    artifacts:
      - build/ipa/*.ipa
      - build/*.log
      - build/pod_install.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
